### ISSUE TITLE
Request to add: unreachable

### ISSUE THREAD

**Issue by Jack-Works** [tc39-transfer/proposal-function-helpers#21]
Implementation: (maybe `Function.unreachable`)

```js
function unreachable(_val) {
    throw new TypeError()
}
```

Usage:

```js
function route(direction) {
    switch (direction) {
        case "up": case "down": return "left";
        case "left": case "right": return "up";
        default: Function.unreachable(direction)
    }
}
```

The real power of this helper is used with TypeScript. This function should have type signature `(val: never) => never`

```ts
type Direction = 'up' | 'down' | 'left' | 'right'
function route(direction: Direction) {
    switch (direction) {
        case "up": case "down": return "left";
        case "left": case "right": return "up";
        default: Function.unreachable(direction)
    }
}
```

It will provide an exhaustive matching guard, which means if I'm missing some cases, it will become a compile error.

Let's say I add one new direction to the type `Direction`

```ts
type Direction = 'up' | 'down' | 'left' | 'right' | 'stay'
```

![image](https://user-images.githubusercontent.com/5390719/139466214-cfc36f84-7bbb-4d23-81a8-537fd8569b37.png)

The compiler will tell me that: hey! `direction` is no longer type `never` (when you exhaustive all possibilities of a variable), you still have one case to check!

This `unreachable` function is very useful and I have implemented it in many of my repos.

**Comment by jridgewell** [comment]
I've used this before when doing exhaustive switch statements (like the OP). It's also common in iterations that never cease:

```js
function ex() {
  while (true) {
    if (someCondition()) return;
  }

  throw new TypeError('unreachable');
}
```

More common in C++ code, because the type has to be proven, but I've done the exact same in JS.

**Comment by ljharb** [comment]
so this is basically "expose %ThrowTypeError%, but with a customized error message about unreachability"?

**Comment by Jack-Works** [comment]
> so this is basically "expose %ThrowTypeError%, but with a customized error message about unreachability"?

There is a value passed in, so I think it's clear about what variable is not exhaustive matched and where it happened.

**Comment by ljharb** [comment]
Why would you pass a value in, and why always only one? If it’s unreachable, you aren’t using the value anyways.

**Comment by jridgewell** [comment]
See the TS example in OP. By passing a parameter, typescript well worn while type checking. Our actual 262 need not have a parameter, but if TS defines one and gives it a `never` type, it gives an extremely pleasant dev experience.

**Comment by ljharb** [comment]
This seems like it’d be better handled by some kind of TS-only syntax, rather than adding something to JS.

**Comment by js-choi** [comment]
Thanks for opening this issue. ￼This would need to be proposed as a separate proposal, as per the most recent plenary’s feedback￼ (https://github.com/tc39-transfer/proposal-function-helpers/issues/17#issuecomment-953814353).

I see an analogy between this function and “never”/“nothing” parsers in parser-combinator libraries, which intrigues me a little. 

But I don’t really see any use cases other than static checking external to JavaScript itself. Would it always throw a TypeError with a blank message? Is there no way to make it more generally useful?

**Comment by Jack-Works** [comment]
> Why would you pass a value in, and why always only one? If it’s unreachable, you aren’t using the value anyways.

No, when you forgot to handle some possibility, it will halt the program at runtime instead of making the program into a bad state.

**Comment by js-choi** [comment]
Like I mentioned in https://github.com/tc39-transfer/proposal-function-helpers/issues/21#issuecomment-955144067, this unreachable function would need to be a separate proposal. I will not be able to create and champion such a separate proposal for this function, mostly due to limited bandwidth. If you’re interested, I encourage you to create your own proposal! : )
